  pipeline {
    agent any
    environment {
      WORKER_IP = '43.205.255.115'
      DOCKERHUB_IMAGE = 'udayparkar/bookstore-app:latest'
    }
    stages {
      stage('Deploy to k8s') {
        steps {
          sh '''
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/ud_key.pem ubuntu@${WORKER_IP} "export KUBECONFIG=/home/ubuntu/kubeconfig && kubectl patch deployment bookstore -p '{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"'$(date +'%s')'\"}}}}' && kubectl set image deployment/bookstore bookstore=${DOCKERHUB_IMAGE} --record"
          '''
        }
      }
      stage('Verify Deployment') {
        steps {
          sh '''
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/ud_key.pem ubuntu@${WORKER_IP} "export KUBECONFIG=/home/ubuntu/kubeconfig && kubectl rollout status deployment/bookstore"
          '''
        }
      }
    }
  }
